name: .NET

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
    - name: Setup SonarCloud
      uses: sonarsource/sonarcloud-github-action@master
      with:
        sonarLogin: ${{ secrets.SONAR_TOKEN }}
    - name: Run SonarCloud Analysis
      run: dotnet sonarscanner begin /k:"newtonCD_dotnet-webapi-template" /d:sonar.login="${{ secrets.SONAR_TOKEN }}" /d:sonar.cs.opencover.reportsPaths="**/coverage.opencover.xml"
    - name: Rebuild for SonarCloud
      run: dotnet build --no-restore
    - name: End SonarCloud Analysis
      run: dotnet sonarscanner end /d:sonar.login="${{ secrets.SONAR_TOKEN }}"
